config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self):
        return {
            'env_color': settings.ENV_COLOR,
            'env_name': settings.ENV_NAME,
        }


urlpatterns = [
    url(r"^$", Home.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r"^users/", include("sfdoc.users.urls", namespace="users")),
    url(r"^accounts/", include("allauth.urls")),
    # Django-RQ
    url(r"^django-rq/", include("django_rq.urls")),
    # publish app
    url(r"^publish/", include("sfdoc.publish.urls", namespace="publish")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

sfdoc/publish/urls.py
from django.conf.urls import url

from . import views

app_name = "publish"

urlpatterns = [
    url(
        regex=r"^$",
        view=views.index,
        name="index",
    ),
    url(
        regex=r"^bundles/$",
        view=views.bundles,
        name="bundles",
    ),
    url(
        regex=r"^bundles/(?P<pk>\d+)/$",
        view=views.bundle,
        name="bundle",
    ),
    url(
        regex=r"^bundles/(?P<pk>\d+)/logs/$",
        view=views.logs,
        name="logs",
    ),
    url(
        regex=r"^bundles/(?P<pk>\d+)/requeue/$",
        view=views.requeue,
        name="requeue",
    ),
    url(
        regex=r"^bundles/(?P<pk>\d+)/review/$",
        view=views.review,
        name="review",
    ),
    url(
        regex=r"^webhook/$",
        view=views.webhook,
        name="webhook",
    ),
]

sfdoc/users/urls.py
from django.conf.urls import url

from . import views

app_name = "users"

urlpatterns = [
    url(regex=r"^$", view=views.UserListView.as_view(), name="list"),
    url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
]

sfdoc/users/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

sfdoc/publish/forms.py
from django import forms


class PublishToProductionForm(forms.Form):
    APPROVE = "A"
    REJECT = "R"
    confirm = forms.BooleanField(label="I have reviewed all changes")
    choice = forms.ChoiceField(
        choices=((APPROVE, "Approve"), (REJECT, "Reject")),
        label="Approve/Reject",
    )

    def approved(self):
        return self.cleaned_data["choice"] == self.APPROVE


class RequeueBundleForm(forms.Form):
    pass

sfdoc/publish/views.py
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.conf import settings
from django import template

from .forms import PublishToProductionForm
from .forms import RequeueBundleForm
from .logger import get_logger
from .models import Article
from .models import Bundle
from .models import Image
from .models import Webhook
from .salesforce import get_community_base_url
from .tasks import process_bundle_queues
from .tasks import process_webhook
from .tasks import publish_drafts

common_context = {
    "env_color": settings.ENV_COLOR,
    "env_name": settings.ENV_NAME,
}


@never_cache
@staff_member_required
def bundle(request, pk):
    bundle = get_object_or_404(Bundle, pk=pk)
    logs = reversed(bundle.logs.all().order_by("-time")[:10])
    context = {
        "bundle": bundle,
        "logs": logs,
        "ready_for_review": bundle.status == Bundle.STATUS_DRAFT,
        **common_context,
    }
    return render(request, "bundle.html", context=context)


@never_cache
@staff_member_required
def bundles(request):
    qs = Bundle.objects.all().order_by("-time_last_modified")
    count = request.GET.get("count", 25)
    page = request.GET.get("page")
    paginator = Paginator(qs, count)
    try:
        bundles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        bundles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        bundles = paginator.page(paginator.num_pages)
    context = {
        "bundles": bundles,
        **common_context,
    }
    if bundles.has_previous():
        context["link_previous"] = "?page={}&count={}".format(
            bundles.previous_page_number(),
            count,
        )
    if bundles.has_next():
        context["link_next"] = "?page={}&count={}".format(
            bundles.next_page_number(),
            count,
        )
    return render(request, "bundles.html", context=context)


@never_cache
@staff_member_required
def index(request):
    context = {
        "processing": Bundle.objects.filter(
            status=Bundle.STATUS_PROCESSING,
        ),
        "draft": Bundle.objects.filter(
            status=Bundle.STATUS_DRAFT,
        ),
        "waiting": Bundle.objects.filter(
            status=Bundle.STATUS_PUBLISH_WAIT,
        ),
        "publishing": Bundle.objects.filter(
            status=Bundle.STATUS_PUBLISHING,
        ),
        "queued": Bundle.objects.filter(
            status=Bundle.STATUS_QUEUED,
        ).order_by("time_queued"),
        **common_context,
    }
    return render(request, "index.html", context=context)


@never_cache
@staff_member_required
def logs(request, pk):
    bundle = get_object_or_404(Bundle, pk=pk)
    logs = bundle.logs.all().order_by("time")
    context = {
        "bundle": bundle,
        "logs": logs,
        **common_context,
    }
    return render(request, "logs.html", context=context)


@never_cache
@staff_member_required
def requeue(request, pk):
    bundle = get_object_or_404(Bundle, pk=pk)
    if not bundle.is_complete():
        return HttpResponseRedirect("../")
    context = {
        "bundle": bundle,
        **common_context,
    }
    if request.method == "POST":
        form = RequeueBundleForm(request.POST)
        if form.is_valid() and request.POST["choice"] == "Requeue":
            newbundle = Bundle.objects.create(
                easydita_id=bundle.easydita_id,
                easydita_resource_id=bundle.easydita_resource_id,
            )

            newbundle.enqueue()
            logger = get_logger(newbundle)
            logger.info("Requeued %s", newbundle)
            process_bundle_queues.delay()
        return HttpResponseRedirect("../")
    else:
        form = RequeueBundleForm()
    return render(request, "requeue.html", context=context)


@never_cache
@staff_member_required
def review(request, pk):
    bundle = get_object_or_404(Bundle, pk=pk)
    logger = get_logger(bundle)
    if bundle.status != Bundle.STATUS_DRAFT:
        return HttpResponseRedirect("../")
    context = {
        "bundle": bundle,
        **common_context,
    }
    if request.method == "POST":
        form = PublishToProductionForm(request.POST)
        if form.is_valid():
            if form.approved():
                logger.info("Approved %s", bundle)
                bundle.status = Bundle.STATUS_PUBLISH_WAIT
                bundle.save()
                publish_drafts.delay(bundle.pk)
            else:
                logger.info("Rejected %s", bundle)
                bundle.status = Bundle.STATUS_REJECTED
                bundle.save()
                process_bundle_queues.delay()
        return HttpResponseRedirect("../")
    else:
        form = PublishToProductionForm()

    base_url = get_community_base_url()
    assert base_url is not None

    def get_articles_for_view(collection):
        return [
            {
                "preview_url": f"{base_url}{article.preview_url}",
                "url_name": article.url_name,
            }
            for article in collection
        ]

    context = {
        "bundle": bundle,
        **common_context,
        "form": form,
        "articles_new": get_articles_for_view(
            bundle.articles.filter(status=Article.STATUS_NEW).order_by("url_name")
        ),
        "articles_changed": get_articles_for_view(
            bundle.articles.filter(status=Article.STATUS_CHANGED).order_by("url_name")
        ),
        "articles_deleted": get_articles_for_view(
            bundle.articles.filter(status=Article.STATUS_DELETED).order_by("url_name")
        ),
        "images_new": bundle.images.filter(status=Image.STATUS_NEW).order_by(
            "filename"
        ),
        "images_changed": bundle.images.filter(status=Image.STATUS_CHANGED).order_by(
            "filename"
        ),
        "images_deleted": bundle.images.filter(status=Image.STATUS_DELETED).order_by(
            "filename"
        ),
    }
    return render(request, "publish.html", context=context)


@never_cache
@csrf_exempt
@require_POST
def webhook(request):
    """Receive webhook from easyDITA."""
    webhook = Webhook.objects.create(body=request.body.decode("utf-8"))
    process_webhook.delay(webhook.pk)
    return HttpResponse("OK")

sfdoc/users/views.py
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = [
        "name",
    ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

sfdoc/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

sfdoc/templates/base.html
{% load static %}
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="pragma" content="no-cache">
    <title>{% block title %}sfdoc{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    {% endblock %}

  </head>

  <body>
    <div class="m-b-1">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="border-color: {{ env_color }}">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">sfdoc</a>
        {% if env_name %}
        <div class="badge env-name" style="background-color: {{ env_color }}">{{ env_name }}</div>
        {% endif %}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'publish:index'  %}">{% trans "Publish" %}</a>
            </li>
            {% endif %}
            {% if request.user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
            </li>
            {% endif %}
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <br>
    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Your stuff: Third-party javascript libraries go here -->
      <script type="text/javascript" src="{% static 'js/jquery-3.1.1.slim.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/tether.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}
  </body>
</html>