config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self):
        return {
            'env_color': settings.ENV_COLOR,
            'env_name': settings.ENV_NAME,
        }


urlpatterns = [
    url(r"^$", Home.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r"^users/", include("sfdoc.users.urls", namespace="users")),
    url(r"^accounts/", include("allauth.urls")),
    # Django-RQ
    url(r"^django-rq/", include("django_rq.urls")),
    # publish app
    url(r"^publish/", include("sfdoc.publish.urls", namespace="publish")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

sfdoc/publish/urls.py
from django.conf.urls import url

from . import views

app_name = "publish"

urlpatterns = [
    url(
        regex=r"^$",
        view=views.index,
        name="index",
    ),
    url(
        regex=r"^bundles/$",
        view=views.bundles,
        name="bundles",
    ),
    url(
        regex=r"^bundles/(?P<pk>\d+)/$",
        view=views.bundle,
        name="bundle",
    ),
    url(
        regex=r"^bundles/(?P<pk>\d+)/logs/$",
        view=views.logs,
        name="logs",
    ),
    url(
        regex=r"^bundles/(?P<pk>\d+)/requeue/$",
        view=views.requeue,
        name="requeue",
    ),
    url(
        regex=r"^bundles/(?P<pk>\d+)/review/$",
        view=views.review,
        name="review",
    ),
    url(
        regex=r"^webhook/$",
        view=views.webhook,
        name="webhook",
    ),
]

sfdoc/publish/models.py
from traceback import format_exception
from urllib.parse import urljoin

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.timezone import now

from .logger import get_logger


class Article(models.Model):
    """Tracks created/updated articles per bundle."""

    class Meta:
        unique_together = [["bundle", "url_name"]]

    STATUS_NEW = "N"
    STATUS_CHANGED = "C"
    STATUS_DELETED = "D"
    status = models.CharField(
        max_length=1,
        choices=(
            (STATUS_NEW, "New"),
            (STATUS_CHANGED, "Changed"),
            (STATUS_DELETED, "Deleted"),
        ),
    )
    bundle = models.ForeignKey(
        "Bundle",
        on_delete=models.CASCADE,
        related_name="articles",
    )
    ka_id = models.CharField(max_length=18)
    kav_id = models.CharField(max_length=18)
    title = models.CharField(max_length=255, default="")
    url_name = models.CharField(max_length=255, default="")

    def __str__(self):
        return "{} ({}) - {} : {}".format(
            self.title, self.url_name, self.status, self.bundle
        )

    @property
    def docset_id(self):
        return self.bundle.docset_id

    @property
    def preview_url(self):
        return "{}?id={}{}".format(
            settings.SALESFORCE_ARTICLE_PREVIEW_URL_PATH_PREFIX,
            self.ka_id,
            "&preview=true&pubstatus=d&channel=APP",
        )


class Bundle(models.Model):
    """Represents a ZIP file of HTML and images from easyDITA."""

    STATUS_NEW = "N"  # newly received webhook from easyDITA
    STATUS_QUEUED = "Q"  # added to processing queue
    STATUS_PROCESSING = "C"  # processing bundle to upload drafts
    STATUS_DRAFT = "D"  # drafts uploaded and ready for review
    STATUS_REJECTED = "R"  # drafts have been rejected
    STATUS_PUBLISH_WAIT = "W"  # drafts are waiting for a worker to publish them
    STATUS_PUBLISHING = "G"  # drafts are being published
    STATUS_PUBLISHED = "P"  # drafts have been published
    STATUS_ERROR = "E"  # error processing bundle
    easydita_id = models.CharField(max_length=255, unique=False)
    easydita_resource_id = models.CharField(max_length=255)
    description = models.CharField(max_length=255, default="(no description)")
    error_message = models.TextField(default="", blank=True)
    logs = GenericRelation("Log")
    status_names = (
        (STATUS_NEW, "New"),
        (STATUS_QUEUED, "Queued"),
        (STATUS_PROCESSING, "Processing"),
        (STATUS_DRAFT, "Ready for Review"),
        (STATUS_REJECTED, "Rejected"),
        (STATUS_PUBLISHING, "Publishing"),
        (STATUS_PUBLISH_WAIT, "Waiting to Publish"),
        (STATUS_PUBLISHED, "Published"),
        (STATUS_ERROR, "Error"),
    )
    status = models.CharField(
        max_length=1,
        choices=status_names,
        default=STATUS_NEW,
    )
    time_queued = models.DateTimeField(null=True, blank=True)
    time_processed = models.DateTimeField(null=True, blank=True)
    time_published = models.DateTimeField(null=True, blank=True)
    time_last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "easyDITA bundle {} - {}".format(self.pk, self.docset.display_name)

    def is_complete(self):
        return self.status in (
            self.STATUS_PUBLISHED,
            self.STATUS_REJECTED,
            self.STATUS_ERROR,
        )

    def get_absolute_url(self):
        return "/publish/bundles/{}/".format(self.pk)

    def enqueue(self):
        assert self.status == self.STATUS_NEW
        self.status = self.STATUS_QUEUED
        self.time_queued = now()
        self.save()

    def set_error(self, e):
        """Set error status and message."""
        tb_list = format_exception(None, e, e.__traceback__)
        self.error_message = "".join(tb_list)
        self.status = self.STATUS_ERROR
        self.save()
        logger = get_logger(self)
        logger.error(self.error_message)

    @property
    def url(self):
        """The easyDITA URL for the bundle."""
        return "{}/rest/all-files/{}/bundle".format(
            settings.EASYDITA_INSTANCE_URL,
            self.easydita_id,
        )

    @property
    def docset_id(self):
        return self.easydita_resource_id

    @property
    def docset(self):
        return Docset.get_or_create_by_docset_id(self.docset_id)


class Image(models.Model):
    STATUS_NEW = "N"
    STATUS_CHANGED = "C"
    STATUS_DELETED = "D"
    status = models.CharField(
        max_length=1,
        choices=(
            (STATUS_NEW, "New"),
            (STATUS_CHANGED, "Changed"),
            (STATUS_DELETED, "Deleted"),
        ),
    )
    bundle = models.ForeignKey(
        "Bundle",
        on_delete=models.CASCADE,
        related_name="images",
    )
    filename = models.CharField(max_length=255)

    def __str__(self):
        return "Image {}: {}".format(self.pk, self.filename)

    @staticmethod
    def get_docset_s3_path(docset_id, draft):
        assert isinstance(draft, bool), type(draft)
        if draft:
            status_directory = settings.AWS_S3_DRAFT_IMG_DIR
        else:
            status_directory = settings.AWS_S3_PUBLIC_IMG_DIR

        assert status_directory.endswith("/")

        docset_path = urljoin(status_directory, docset_id) + "/"
        return docset_path

    @staticmethod
    def get_storage_path(docset_id, imagepath, draft):
        fullpath = urljoin(Image.get_docset_s3_path(docset_id, draft), imagepath)
        return fullpath

    @staticmethod
    def get_url(docset_id, imagepath, draft):
        images_root_url = "https://{}.s3.amazonaws.com/".format(
            settings.AWS_S3_BUCKET,
        )

        return (
            f"{images_root_url}{(Image.get_storage_path(docset_id, imagepath, draft))}"
        )

    # Draft images are located in settings.AWS_S3_DRAFT_IMG_DIR
    # Production images are located in settings.AWS_S3_PUBLIC_IMG_DIR
    @staticmethod
    def draft_url_or_path_to_public(draft_storage_path):
        return draft_storage_path.replace(
            settings.AWS_S3_DRAFT_IMG_DIR, settings.AWS_S3_PUBLIC_IMG_DIR
        )

    @staticmethod
    def public_url_or_path_to_draft(draft_storage_path):
        return draft_storage_path.replace(
            settings.AWS_S3_PUBLIC_IMG_DIR, settings.AWS_S3_DRAFT_IMG_DIR
        )

    def _get_url(self, draft):
        return Image.get_url(self.docset_id, self.filename, draft)

    @property
    def draft_storage_path(self):
        return Image.get_storage_path(self.docset_id, self.filename, draft=True)

    @property
    def public_storage_path(self):
        return Image.get_storage_path(self.docset_id, self.filename, draft=False)

    @property
    def url_draft(self):
        return self._get_url(True)

    @property
    def url_production(self):
        return self._get_url(False)

    @property
    def docset_id(self):
        return self.bundle.docset_id


class Log(models.Model):
    content_object = GenericForeignKey("content_type", "object_id")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    message = models.TextField()
    object_id = models.PositiveIntegerField()
    time = models.DateTimeField(auto_now_add=True)

    def get_message(self):
        return "{} {}".format(
            self.time.strftime("%Y-%m-%dT%H:%M:%S"),
            self.message,
        )


class Webhook(models.Model):
    STATUS_NEW = "N"  # not yet processed
    STATUS_ACCEPTED = "A"  # webhook added bundle to processing queue
    STATUS_REJECTED = "R"  # bundle already processing or queued
    body = models.TextField()
    bundle = models.ForeignKey(
        "Bundle",
        on_delete=models.CASCADE,
        related_name="webhooks",
        null=True,
        blank=True,
    )
    status = models.CharField(
        max_length=1,
        choices=(
            (STATUS_NEW, "New"),
            (STATUS_ACCEPTED, "Accepted"),
            (STATUS_REJECTED, "Rejected"),
        ),
        default=STATUS_NEW,
    )
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Webhook {}".format(self.pk)

    @property
    def docset_id(self):
        return self.bundle.docset_id


class Docset(models.Model):
    """Represents a persistent set of documents pubished together, such as a
    user guide or tutorial series. Every bundle is associated with a Docset
    in a many to one relationship. Docsets have index articles and tiles in
    PowerOfUs Hub."""

    docset_id = models.CharField(max_length=255)
    name = models.CharField(max_length=255, default="")
    index_article_url = models.CharField(
        max_length=255,
        null=True,
    )
    index_article_ka_id = models.CharField(
        max_length=64,
        null=True,
    )

    @classmethod
    def get_or_create_by_docset_id(cls, docset_id):
        obj, created = cls.objects.get_or_create(docset_id=docset_id)
        return obj

    @property
    def display_name(self):
        return self.name or self.docset_id


class AllowedLinkset(models.Model):
    """Each model is a newline-separated list of allowed links in flat or regexp format."""

    name = models.CharField(max_length=100, unique=True, null=True)
    urls = models.TextField()

    @classmethod
    def all_urls(cls):
        """Every URL from every LinkSet"""
        all_urls = []
        for obj in cls.objects.all():
            all_urls.extend(obj.urllist)
        return all_urls

    @property
    def urllist(self):
        """Urls as a list instead of a string"""
        return [url.strip() for url in self.urls.split("\n")]

sfdoc/publish/forms.py
from django import forms


class PublishToProductionForm(forms.Form):
    APPROVE = "A"
    REJECT = "R"
    confirm = forms.BooleanField(label="I have reviewed all changes")
    choice = forms.ChoiceField(
        choices=((APPROVE, "Approve"), (REJECT, "Reject")),
        label="Approve/Reject",
    )

    def approved(self):
        return self.cleaned_data["choice"] == self.APPROVE


class RequeueBundleForm(forms.Form):
    pass

sfdoc/publish/templates/all_published.html
{% extends 'base.html' %}

{% block content %}
<h3>All easyDITA bundles have been successfully published!</h3>
{% endblock content %}

sfdoc/publish/templates/bundle.html
{% extends 'base.html' %}

{% block content %}
<h4>{{ bundle }}</h4>
<p><a href="{% url 'publish:bundles' %}">View all bundles</a></p>

<br>
<table class="table">
  <tr>
    <th>easyDITA ID</th>
    <th>Status</th>
    <th>Time Last Modified</th>
  </tr>
  <tr>
    <td>{{ bundle.easydita_id }}</td>
    <td>{{ bundle.get_status_display }}</td>
    <td>{{ bundle.time_last_modified }}</td>
  </tr>
</table>

{% if ready_for_review %}
<br>
<h5>Ready for Review</h5>
<p><a href="review/">Review draft articles and images<a></p>
{% elif bundle.is_complete %}
<br>
<button type="button" class="btn btn-primary" onclick="location.href='requeue/'">Requeue</button>
<br>
{% endif %}

{% if bundle.error_message %}
<br>
<h5>Error Message</h5>
<span class="border">
  <pre>{{ bundle.error_message }}</pre>
</span>
{% endif %}

{% if logs %}
<br>
<h5>Logs</h5>
<p><a href="logs/">View all logs</a></p>
<span class="border">
<pre>
{% for log in logs %}{{ log.get_message }}
{% endfor %}</pre>
</span>
{% endif %}

{% endblock content %}

sfdoc/publish/templates/bundles.html
{% extends 'base.html' %}

{% block content %}
<h4>easyDITA Bundles</h4>

<br>
<table class="table">
  <tr>
    <th>#</th>
    <th>Docset</th>
    <th>Status</th>
    <th>Time Last Modified</th>
    <th>easyDITA ID</th>
  </tr>
{% for bundle in bundles %}
  <tr>
    <td><a href="{{ bundle.get_absolute_url}} ">{{ bundle.pk }}</a></td>
    <td>{{ bundle.docset.name }}</td>
    <td>{{ bundle.get_status_display }}</td>
    <td>{{ bundle.time_last_modified }}</td>
    <td>{{ bundle.easydita_id }}</td>
  </tr>
{% endfor %}
</table>

{% if link_previous or link_next %}
<ul class="pagination">
{% if link_previous %}
  <li class="page-item">
    <a class="page-link" href="{{ link_previous }}">Previous</a>
  </li>
{% endif %}
{% if link_next %}
  <li class="page-item">
    <a class="page-link" href="{{ link_next }}">Next</a>
  </li>
{% endif %}
</ul>
<p>Page {{ bundles.number }} of {{ bundles.paginator.num_pages }}</p>
{% endif %}

{% endblock content %}

sfdoc/publish/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h4>easyDITA Bundle Processing Queue</h4>
<p><a href="{% url 'publish:bundles' %}">View all bundles</a></p>

{% if processing %}
<br>
<h5>Processing</h5>
<ul>
{% for bundle in processing %}
  <li><a href="{{ bundle.get_absolute_url }}">{{ bundle }}</a></li>
{% endfor %}
</ul>
{% endif %}

{% if draft %}
<br>
<h5>Ready for Review</h5>
<ul>
{% for bundle in draft %}
  <li><a href="{{ bundle.get_absolute_url }}">{{ bundle }}</a></li>
{% endfor %}
</ul>
{% endif %}

{% if waiting %}
<br>
<h5>Waiting to be Published</h5>
<ul>
{% for bundle in waiting %}
  <li><a href="{{ bundle.get_absolute_url }}">{{ bundle }}</a></li>
{% endfor %}
</ul>
{% endif %}


{% if publishing %}
<br>
<h5>Publishing</h5>
<ul>
{% for bundle in publishing %}
  <li><a href="{{ bundle.get_absolute_url }}">{{ bundle }}</a></li>
{% endfor %}
</ul>
{% endif %}

{% if queued %}
<br>
<h5>Queued</h5>
<ol>
{% for bundle in queued %}
  <li><a href="{{ bundle.get_absolute_url }}">{{ bundle }}</a></li>
{% endfor %}
</ol>
{% endif %}

{% if not processing and not draft and not publishing and not queued %}
<p>There are no easyDITA bundles in the queue</p>
{% endif %}

{% endblock content %}

sfdoc/publish/templates/logs.html
{% extends 'base.html' %}

{% block content %}
<h4>{{ bundle }} Logs</h4>
<p><a href="../">Back to bundle overview</a></p>

{% if logs %}
<br>
<h5>Logs</h5>
<span class="border">
<pre>
{% for log in logs %}{{ log.get_message }}
{% endfor %}</pre>
</span>
{% endif %}

{% endblock content %}

sfdoc/publish/templates/publish.html
{% extends 'base.html' %}

{% block content %}
<h4>Review draft articles and images from {{ bundle }}</h4>

{% if articles_new %}
<br>
<h5>New Articles</h5>
<p>
  <ul>
{% for article in articles_new %}
    <li><a href="{{ article.preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if articles_changed %}
<br>
<h5>Changed Articles</h5>
<p>
  <ul>
{% for article in articles_changed %}
    <li><a href="{{ article.preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if articles_deleted %}
<br>
<h5>Deleted Articles</h5>
<p>
  <ul>
{% for article in articles_deleted %}
    <li><a href="{{ article.preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if images_new %}
<br>
<h5>New Images</h5>
<p>
  <ul>
{% for image in images_new %}
    <li><a href="{{ image.url_draft }}" target="_blank">{{ image.filename }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if images_changed %}
<br>
<h5>Changed Images</h5>
<p>
  <ul>
{% for image in images_changed %}
    <li><a href="{{ image.url_draft }}" target="_blank">{{ image.filename }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if images_deleted %}
<br>
<h5>Deleted Images</h5>
<p>
  <ul>
{% for image in images_deleted %}
    <li><a href="{{ image.url_production }}" target="_blank">{{ image.filename }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

<br>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Submit" /></p>
</form>

{% endblock content %}

sfdoc/publish/templates/publish_drafts.html
{% extends 'base.html' %}

{% block content %}
<h3>Publish drafts from easyDITA bundle {{ bundle.easydita_id }}</h3>
<p>By checking the box below, you acknowledge that you have reviewed the drafts and that no further changes are needed before publishing.</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <p><input type="submit" value="Submit" /></p>
</form>
{% endblock content %}

sfdoc/publish/templates/publish_form.html
{% extends 'base.html' %}

{% block content %}
<h4>Review draft articles and images from easyDITA bundle {{ bundle.pk }}</h4>

{% if articles_new %}
<br>
<h5>New Articles</h5>
<p>
  <ul>
{% for article in articles_new %}
    <li><a href="{{ article.draft_preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if articles_changed %}
<br>
<h5>Changed Articles</h5>
<p>
  <ul>
{% for article in articles_changed %}
    <li><a href="{{ article.draft_preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if images_new %}
<br>
<h5>New Images</h5>
<p>
  <ul>
{% for image in images_new %}
    <li><a href="{{ image.draft_preview_url }}" target="_blank">{{ image.filename }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if images_changed %}
<br>
<h5>Changed Images</h5>
<p>
  <ul>
{% for image in images_changed %}
    <li><a href="{{ image.draft_preview_url }}" target="_blank">{{ image.filename }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

<br>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Submit" /></p>
</form>

{% endblock content %}

sfdoc/publish/templates/publish_to_production.html
{% extends 'base.html' %}

{% block content %}
<h3>Publish drafts from easyDITA bundle {{ easydita_bundle_id }}</h3>
<p>By checking the box below, you acknowledge that you have reviewed the drafts and that no further changes are needed before publishing.</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <p><input type="submit" value="Submit" /></p>
</form>
{% endblock content %}

sfdoc/publish/templates/queue_status.html
{% extends 'base.html' %}

{% block content %}
<h3>easyDITA bundle processing queue</h3>
{% if bundle %}
<br>
<h4>Currently Processing</h4>
<a href="{{ bundle.get_absolute_url }}">easyDITA bundle {{ bundle.easydita_id }}: {{ bundle.get_status_display }}</a>
{% endif %}
{% if queue %}
<br><br>
<h4>In Queue</h4>
<ol>
{% for item in queue %}
  <li><a href="{{ item.get_absolute_url }}">easyDITA bundle {{ item.easydita_id }}: {{ item.get_status_display }}</a></li>
{% endfor %}
</ol>
{% endif %}
{% endblock content %}

sfdoc/publish/templates/requeue.html
{% extends 'base.html' %}

{% block content %}
<h4>Requeue {{ bundle }}</h4>

<br>
<h5>Are you sure you want to requeue {{ bundle }}?</h5>
<br>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="choice" class="btn btn-secondary" value="Cancel"  />
    <input type="submit" name="choice" class="btn btn-primary"   value="Requeue" />
</form>

{% endblock content %}

sfdoc/publish/templates/review.html
{% extends 'base.html' %}

{% block content %}
<h4>Review draft articles and images from {{ bundle }}</h4>

{% if articles_new %}
<br>
<h5>New Articles</h5>
<p>
  <ul>
{% for article in articles_new %}
    <li><a href="{{ article.preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if articles_changed %}
<br>
<h5>Changed Articles</h5>
<p>
  <ul>
{% for article in articles_changed %}
    <li><a href="{{ article.preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if articles_unchanged %}
<br>
<h5>Unchanged Articles with Changed Images</h5>
<p>
  <ul>
{% for article in articles_unchanged %}
    <li><a href="{{ article.preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if articles_deleted %}
<br>
<h5>Deleted Articles</h5>
<p>
  <ul>
{% for article in articles_deleted %}
    <li><a href="{{ article.preview_url }}" target="_blank">{{ article.url_name }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if images_new %}
<br>
<h5>New Images</h5>
<p>
  <ul>
{% for image in images_new %}
    <li><a href="{{ image.url_draft }}" target="_blank">{{ image.filename }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if images_changed %}
<br>
<h5>Changed Images</h5>
<p>
  <ul>
{% for image in images_changed %}
    <li><a href="{{ image.url_draft }}" target="_blank">{{ image.filename }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

{% if images_deleted %}
<br>
<h5>Deleted Images</h5>
<p>
  <ul>
{% for image in images_deleted %}
    <li><a href="{{ image.url_production }}" target="_blank">{{ image.filename }}</a></li>
{% endfor %}
  </ul>
</p>
{% endif %}

<br>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Submit" /></p>
</form>

{% endblock content %}

sfdoc/publish/templates/status.html
{% extends 'base.html' %}

{% block content %}
<h3>{{ bundle }}</h3>
<br>

<h5>easyDITA ID</h5>
<p>{{ bundle.easydita_id }}</p>

<h5>Status</h5>
<p>{{ bundle.get_status_display }}</p>

{% if bundle.time_queued %}
<h5>Queued</h5>
<p>{{ bundle.time_queued }}</p>
{% endif %}

{% if bundle.time_processed %}
<h5>Processed</h5>
<p>{{ bundle.time_processed }}</p>
{% endif %}

{% if bundle.error_message %}
<h5>Error</h5>
<p>{{ bundle.error_message }}</p>
{% endif %}

{% endblock content %}